@startuml
!include style.puml
!define MAIN_COLOUR #800040
!define COMMONS_COLOR #CCCDC6
skinparam ArrowFontStyle plain

box Storage STORAGE_COLOR_T1
participant ": JsonInsuraBookStorage" as JsonInsuraBookStorage STORAGE_COLOR
participant ": JsonSerializableInsuraBook" as JsonSerializableInsuraBook STORAGE_COLOR
participant ": JsonAdaptedPolicyType" as JsonAdaptedPolicyType STORAGE_COLOR
participant ": JsonAdaptedClient" as JsonAdaptedClient STORAGE_COLOR
participant ": JsonAdaptedPolicy" as JsonAdaptedPolicy STORAGE_COLOR
participant ": JsonAdaptedClaim" as JsonAdaptedClaim STORAGE_COLOR
end box

activate JsonInsuraBookStorage
JsonInsuraBookStorage -> JsonSerializableInsuraBook : toModelType()
activate JsonSerializableInsuraBook

JsonSerializableInsuraBook -> JsonAdaptedPolicyType : toModelType()
JsonSerializableInsuraBook -> JsonAdaptedClient : toModelType()
JsonSerializableInsuraBook -> JsonAdaptedPolicy : toModelType()
JsonSerializableInsuraBook -> JsonAdaptedClaim : toModelType()

JsonSerializableInsuraBook --> JsonInsuraBookStorage : insuraBook
deactivate JsonSerializableInsuraBook

@enduml
