@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyInsuraBook" as ReadOnlyInsuraBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class InsuraBook
Class ModelManager
Class UserPrefs

Class UniqueClientList
Class UniquePolicyList
Class UniquePolicyTypeList
Class Client
Class ClientId
Class Name
Class Portfolio
Class Policy
Class PolicyId
Class PolicyType
Class InsuraDate
Class Claim
Class ClaimId
Class ClientId
Class PolicyId
Class ClaimAmount
Class InsuraDate
Class ClaimMessage

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

InsuraBook .up.|> ReadOnlyInsuraBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInsuraBook
ModelManager -left-> "1" InsuraBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

InsuraBook *--> "1" UniqueClientList
InsuraBook *--> "1" UniquePolicyList
InsuraBook *--> "1" UniquePolicyTypeList
UniqueClientList o--> "~* all" Client
UniquePolicyList --> "~* all" Policy

Client *--> "1" Name
Client *--> "1" ClientId
Client *--> "1" Portfolio

Portfolio *--> "1" UniquePolicyList
Portfolio *--> "attached to" Client

Policy *--> "1" PolicyId
Policy *--> "1" PolicyType
Policy *--> "1" InsuraDate
Policy o--> "0..* claims" Claim

Claim *--> "1" ClaimId
Claim *--> "1" ClientId
Claim *--> "1" PolicyId
Claim *--> "1" ClaimAmount
Claim *--> "1" InsuraDate
Claim ---> "0..1" ClaimMessage


Client -[hidden]up--> I
UniqueClientList -[hidden]right-> I
UniquePolicyList -[hidden]left-> UniqueClientList


ModelManager --> "~* filtered" Client
ModelManager --> "~* filtered" Policy
ModelManager --> "~* filtered" Claim
@enduml
