@startuml
!include style.puml
!define COMMONS_COLOR #CCCDC6
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":StorageManager" as StorageManager STORAGE_COLOR
participant ":JsonInsuraBookStorage" as JsonInsuraBookStorage STORAGE_COLOR
participant ":JsonSerializableInsuraBook" as JsonSerializableInsuraBook STORAGE_COLOR
end box

box Common COMMONS_COLOR
participant ":JsonUtil" as JsonUtil COMMONS_COLOR
end box

[-> LogicManager : execute add policy command
activate LogicManager

LogicManager -> StorageManager : saveInsuraBook(insuraBook)
activate StorageManager

StorageManager -> JsonInsuraBookStorage : saveInsuraBook(insuraBook, filePath)
activate JsonInsuraBookStorage

create JsonSerializableInsuraBook
JsonInsuraBookStorage -> JsonSerializableInsuraBook : (insuraBook)
activate JsonSerializableInsuraBook

JsonSerializableInsuraBook --> JsonInsuraBookStorage : serializableInsuraBook
deactivate JsonSerializableInsuraBook

JsonInsuraBookStorage -> JsonUtil : saveJsonFile(serializableInsuraBook)
activate JsonUtil

JsonUtil -> JsonUtil : write to file
JsonUtil --> JsonInsuraBookStorage
deactivate JsonUtil

JsonInsuraBookStorage --> StorageManager
deactivate JsonInsuraBookStorage


StorageManager --> LogicManager
deactivate StorageManager

[<--LogicManager
deactivate LogicManager

@enduml
