@startuml
!include style.puml
!define COMMONS_COLOR #CCCDC6
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ": StorageManager" as StorageManager STORAGE_COLOR
participant ": JsonInsuraBookStorage" as JsonInsuraBookStorage STORAGE_COLOR
participant ": JsonSerializableInsuraBook" as JsonSerializableInsuraBook STORAGE_COLOR
participant ": JsonAdaptedPolicyType" as JsonAdaptedPolicyType STORAGE_COLOR
participant ": JsonAdaptedClient" as JsonAdaptedClient STORAGE_COLOR
participant ": JsonAdaptedPolicy" as JsonAdaptedPolicy STORAGE_COLOR
participant ": JsonAdaptedClaim" as JsonAdaptedClaim STORAGE_COLOR
end box

box Common COMMONS_COLOR
participant ": JsonUtil" as JsonUtil COMMONS_COLOR
end box

[-> LogicManager : execute add policy command
activate LogicManager

LogicManager -> StorageManager : saveInsuraBook(insuraBook)
activate StorageManager

StorageManager -> JsonInsuraBookStorage : saveInsuraBook(insuraBook, filePath)
activate JsonInsuraBookStorage

create JsonSerializableInsuraBook
JsonInsuraBookStorage -> JsonSerializableInsuraBook : (insuraBook)
activate JsonSerializableInsuraBook

create JsonAdaptedPolicyType
JsonSerializableInsuraBook -> JsonAdaptedPolicyType
activate JsonAdaptedPolicyType
JsonAdaptedPolicyType --> JsonSerializableInsuraBook
deactivate JsonAdaptedPolicyType

create JsonAdaptedClient
JsonSerializableInsuraBook -> JsonAdaptedClient
activate JsonAdaptedClient

create JsonAdaptedPolicy
JsonAdaptedClient -> JsonAdaptedPolicy
activate JsonAdaptedPolicy

create JsonAdaptedClaim
JsonAdaptedPolicy -> JsonAdaptedClaim
activate JsonAdaptedClaim
JsonAdaptedClaim --> JsonAdaptedPolicy
deactivate JsonAdaptedClaim

JsonAdaptedPolicy --> JsonAdaptedClient
deactivate JsonAdaptedPolicy

JsonAdaptedClient --> JsonSerializableInsuraBook
deactivate JsonAdaptedClient
JsonSerializableInsuraBook --> JsonInsuraBookStorage : serializableInsuraBook

JsonInsuraBookStorage -> JsonUtil : saveJsonFile(serializableInsuraBook)
activate JsonUtil

JsonUtil -> JsonUtil : write to file
JsonUtil --> JsonInsuraBookStorage
deactivate JsonUtil

JsonInsuraBookStorage --> StorageManager
deactivate JsonInsuraBookStorage


StorageManager --> LogicManager
deactivate StorageManager

[<--LogicManager
deactivate LogicManager
@enduml